# Generated by Django 5.2.8 on 2025-11-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="название"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес эл. почты",
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="номер дома"
                    ),
                ),
                (
                    "arrears",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="задолженность",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "завод"),
                            (1, "розничная сеть"),
                            (2, "индивидуальный предприниматель"),
                        ],
                        editable=False,
                        verbose_name="уровень",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="поставщик узла сети",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="network.networklink",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "узел сети",
                "verbose_name_plural": "узлы сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="название"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="модель"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(verbose_name="дата выхода продукта на рынок"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="network.networklink",
                        verbose_name="узел сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
